version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: medical-gpt-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE:-gptlink_edu}
      MYSQL_USER: ${DB_USERNAME:-gptlink}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - medical-gpt
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=256M --max-connections=200
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: medical-gpt-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}" --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - medical-gpt
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # PHP后端服务
  gptserver:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: medical-gpt-server
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "9000:80"
      - "9503:9503"
    environment:
      - MEDICAL_MODE=${MEDICAL_MODE:-true}
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE:-gptlink_edu}
      - DB_USERNAME=${DB_USERNAME:-gptlink}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-deepseek-chat}
      - OPENAI_HOST=${OPENAI_HOST:-https://api.deepseek.com}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-2000}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.7}
      - MEDICAL_SAFETY_CHECK=${MED_CONTENT_FILTER:-true}
      - DAILY_REQUEST_LIMIT=${MED_MAX_DAILY_REQUESTS:-100}
      - SESSION_TIMEOUT=${SESSION_LIFETIME:-120}
      - APP_URL=${APP_URL:-http://localhost}
      - COMPOSER_CACHE_DIR=/tmp/composer-cache
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_NO_INTERACTION=1
    volumes:
      - ./gptserver:/var/www/html/gptserver:cached
      - ./gptweb:/var/www/html/gptweb:cached
      - ./gptadmin:/var/www/html/gptadmin:cached
      - ./logs/php:/var/log/php:delegated
      - gptserver_vendor:/var/www/html/gptserver/vendor
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - medical-gpt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx Web服务器
  nginx:
    image: nginx:alpine
    container_name: medical-gpt-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./gptweb:/usr/share/nginx/html/web
      - ./gptadmin:/usr/share/nginx/html/admin
      - nginx_logs:/var/log/nginx
      - ssl_certs:/etc/nginx/ssl
    depends_on:
      - gptserver
    networks:
      - medical-gpt

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  server_logs:
    driver: local
  nginx_logs:
    driver: local
  ssl_certs:
    driver: local
  gptserver_vendor:
    driver: local

networks:
  medical-gpt:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16