services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: medical-gpt-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE:-gptlink_edu}
      MYSQL_USER: ${DB_USERNAME:-gptlink}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - medical-gpt
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: medical-gpt-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - medical-gpt
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Hyperf后端服务
  gptserver:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: medical-gpt-server
    restart: unless-stopped
    ports:
      - "9501:9501"
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE:-gptlink_edu}
      - DB_USERNAME=${DB_USERNAME:-gptlink}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-deepseek-chat}
      - OPENAI_HOST=${OPENAI_HOST:-https://api.deepseek.com}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - medical-gpt

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  medical-gpt:
    driver: bridge