# 医疗健康AI助手 - Prometheus监控配置
# 版本: 2.0
# 说明: 专为阿里云环境优化的监控配置

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'medical-gpt-aliyun'
    environment: 'production'
    region: 'cn-hangzhou'

# 规则文件
rule_files:
  - "rules/*.yml"

# 告警管理器配置 
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter - 系统指标
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'aliyun-ecs'

  # MySQL Exporter - 数据库指标
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis Exporter - Redis指标
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx Exporter - Web服务器指标
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s
    metrics_path: /metrics

  # PHP-FPM Exporter - PHP指标
  - job_name: 'php-fpm-exporter'
    static_configs:
      - targets: ['php-fpm-exporter:9253']
    scrape_interval: 30s
    metrics_path: /metrics

  # Docker容器指标
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # 应用自定义指标
  - job_name: 'medical-gpt-app'
    static_configs:
      - targets: ['gptserver:9000']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Nginx状态监控
  - job_name: 'nginx-status'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 15s
    metrics_path: /nginx_status
    scrape_timeout: 5s

  # 健康检查监控
  - job_name: 'health-check'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 10s
    metrics_path: /health
    scrape_timeout: 5s

# 远程写入配置（可选 - 用于长期存储）
# remote_write:
#   - url: "https://prometheus-remote-write.aliyuncs.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# 远程读取配置（可选）
# remote_read:
#   - url: "https://prometheus-remote-read.aliyuncs.com/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"